#!/usr/bin/env bash

# Descripción: Genera identificadores en minúsculas procesando nombres y apellidos. Compatible con /bin/sh y /bin/bash.
# Entrada: $1: Fichero origen (CSV delimitado por ;).  $2: Fichero destino
# Salida: 

function f_generar_logins_universal() {

    origen="$1"
    destino="$2"

    >"$destino"

    while IFS=";" read nombre ap1 ap2 dni
    do
        iniciales=$(echo "$nombre" | awk '{for(i=1;i<=NF;i++) printf substr($i,1,1)}')

        apellidos=$(echo "$ap1 $ap2" | tr -d ' ')
        tres_ap=$(echo "$apellidos" | cut -c1-3)

        ult_dni=$(echo "$dni" | tail -c 4)

        login=$(echo "$iniciales$tres_ap$ult_dni" | tr '[:upper:]' '[:lower:]')

        echo "$login" >> "$destino"

    done < "$origen"
}

f_generar_logins_universal "$1" "$2"
